djnago_portfolio/blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path("", views.blog_index, name="blog_index"),
    path("<int:pk>/", views.blog_detail, name="blog_detail"),
    path("<category>/", views.blog_category, name="blog_category"),
]

djnago_portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    # add my urls modules path in apps crated like projects below
    path('projects/', include('projects.urls')),
    path("blog/", include("blog.urls")),
]

djnago_portfolio/projects/urls.py
from django.urls import path
from projects import views

app_name = 'projects'
# <int:pk> - used to capture urls path and int in converter pk is primary key id
urlpatterns = [
    path('', views.all_projects, name="all_projects"),
    path('<int:pk>', views.project_details, name="project_details"),
    path('home/', views.home, name="home"),
]

# app_name and name of path will be used to link urls templates

djnago_portfolio/blog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=20)


class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField('Category', related_name='posts')


class Comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

djnago_portfolio/projects/models.py
from django.db import models


# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    # image = models.FilePathField(path='/projects/img')
    image = models.CharField(max_length=100)
# Project(title='Test project',description='This is I am learning Django', technology='Django', image='test1.png')

djnago_portfolio/blog/forms.py
from django import forms


class CommentForm(forms.Form):
    author = forms.CharField(
        max_length=60,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Your Name"
        })
    )
    body = forms.CharField(widget=forms.Textarea(
        attrs={
            "class": "form-control",
            "placeholder": "Leave a comment!"
        })
    )

djnago_portfolio/blog/views.py
from django.shortcuts import render
from blog.models import Post, Comment
from blog.forms import CommentForm


def blog_index(request):
    posts = Post.objects.all().order_by('-created_on')
    context = {
        "posts": posts,
    }
    print('rohan')
    return render(request, "blog_index.html", context)


def blog_category(request, category):
    posts = Post.objects.filter(
        categories__name__contains=category
    ).order_by(
        '-created_on'
    )
    context = {
        "category": category,
        "posts": posts
    }
    return render(request, "blog_category.html", context)


def blog_detail(request, pk):
    post = Post.objects.get(pk=pk)

    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                author=form.cleaned_data["author"],
                body=form.cleaned_data["body"],
                post=post
            )
            comment.save()

    comments = Comment.objects.filter(post=post)
    context = {
        "post": post,
        "comments": comments,
        "form": form,
    }
    return render(request, "blog_detail.html", context)

djnago_portfolio/projects/views.py
from django.shortcuts import render
from django.http import HttpResponse
from projects.models import Project


# Create your views here.

def project_list(request):
    return render(request, 'index.html')


def all_projects(request):
    # query the db to return all project objects
    projects = Project.objects.all()  # ORM to fetch objects from model created in Projects app
    return render(request, 'all_projects.html',
                  {'projects': projects})


# <!--                        <a> herf= "{% url 'app_name:name' arg_value %}"   this helps to link urls using names and args by retrieving correct urls</a>-->

def project_details(request, pk):
    # query the db to return one project objects using pk == id
    project = Project.objects.get(pk=pk)  # ORM to fetch object from model created in Projects app having id as pk
    # keyword below is project to be used inside template structure in html files
    return render(request, 'details.html',
                  {'project': project})


def home(request):
    return render(request, 'home.html')

djnago_portfolio/blog/templates/blog_category.html
{% extends "base.html" %}
{% block content %}
<div class="col-md-8 offset-md-2">
    <h1>{{ category | title }}</h1>
    <hr>
    {% for post in posts %}
        <h2><a href="{% url 'blog:blog_detail' post.pk%}">{{ post.title }}</a></h2>
        <small>
            {{ post.created_on.date }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.categories.all %}
            <a href="{% url 'blog:blog_category' category.name %}">
                {{ category.name }}
            </a>&nbsp;
            {% endfor %}
        </small>
        <p>{{ post.body | slice:":400" }}...</p>
    {% endfor %}
</div>
{% endblock %}

djnago_portfolio/blog/templates/blog_detail.html
{% extends "base.html" %}
{% block content %}
<div class="col-md-8 offset-md-2">
    <h1>{{ post.title }}</h1>
    <small>
        {{ post.created_on.date }} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories.all %}
        <a href="{% url 'blog:blog_category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.body | linebreaks }}</p>
    <h3>Leave a comment:</h3>
    <form action="/blog/{{ post.pk }}/" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.author }}
        </div>
        <div class="form-group">
            {{ form.body }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <h3>Comments:</h3>
    {% for comment in comments %}
    <p>
        On {{comment.created_on.date }}&nbsp;
        <b>{{ comment.author }}</b> wrote:
    </p>
    <p>{{ comment.body }}</p>
    <hr>
    {% endfor %}
</div>
{% endblock %}

djnago_portfolio/blog/templates/blog_index.html
{% extends "base.html" %}
{% block content %}
<div class="col-md-8 offset-md-2">
    <h1>Blog Index</h1>
    <hr>
    {% for post in posts %}
    <h2><a href="{% url 'blog:blog_detail' post.pk%}">{{ post.title }}</a></h2>
    <small>
        {{ post.created_on.date }} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories.all %}
        <a href="{% url 'blog:blog_category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.body | slice:":400" }}...</p>
    {% endfor %}
</div>
{% endblock %}

djnago_portfolio/projects/templates/all_projects.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container">
    <h1>Projects</h1>
    <div class="row">
    {% for project in projects %}
        <div class="col-md-4">
            <div class="card mb-2">
                <img class="card-img-top" src="{% static project.image %}" alt="{{ project.description }}">
                <div class="card-body">
                    <h5 class="card-title">{{ project.title }}</h5>
                    <p class="card-text">{{ project.description }}</p>
                    <a href="{% url 'projects:project_details' project.pk %}" class="btn btn-primary">Read More</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>

{% endblock %}

djnago_portfolio/projects/templates/all_projects_practise.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All projects</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <h1>Hello from all_projects</h1>
<!--    {{ projects }} this syntax used to pass variables passed in render as dict key-->
<!--  below used in templating for loop syntax  -->
    {% for project in projects %}
        <img src="{% static project.image %}" alt="oh it is missing">
        <h1>{{ project.title }}</h1>
        <p>{{ project.description }}</p>
        <p>{{ project.technology }}</p>
    {% endfor %}
</body>
</html>

djnago_portfolio/projects/templates/details.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <h1>{{ project.title }}</h1>
    <div class="row">
        <div class="col-md-8">
            <img src="{% static project.image %}" alt="{{ project.description }}" width="100%">
        </div>
        <div class="col-md-4">
            <h5>About the project</h5>
            <p>{{ project.description }}</p>
            <h5>Built with:</h5>
            <p>{{ project.technology }}</p>
        </div>
    </div>

{% endblock %}

djnago_portfolio/projects/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <h1>Welcome to My Project Portfolio</h1>
    <div class="row">
        <div class="col-md-8">
            <img src="{% static 'projects/img/ROHAN_FAMILY_DAY.jpg' %}" alt="missing" width="100%">
        </div>
        <div class="col-md-4">
            <h4>About the author:</h4>
            <p>Rohan Mukund Miraje</p>
            <p>Software developer</p>
            <h5>Skills:</h5>
            <p>Python developer, DSA, problem solving, multiprocessing, linux, django</p>
        </div>
    </div>

{% endblock %}

djnago_portfolio/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Portfolio</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'projects:all_projects' %}">Portfolio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'projects:home' %}">Home</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:blog_index' %}">Blog</a>
            </li>
          </ul>
        </div>

    </div>
</nav>

<div class="container">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>